name: IPTV Playlist Auto Update

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Genera playlist
        run: |
          echo "#EXTM3U" > playlist.m3u

          API="https://api.github.com/repos/sahind01/mutcats/contents/selcuk"

          FILES=$(curl -s $API | grep -o '"name":"[^"]*\.m3u8"' | cut -d'"' -f4)

          for file in $FILES
          do
            NAME=$(echo $file | sed 's/.m3u8//g' | tr '-' ' ')
            URL="https://raw.githubusercontent.com/sahind01/mutcats/main/selcuk/$file"

            echo "#EXTINF:-1,$NAME" >> playlist.m3u
            echo "$URL" >> playlist.m3u
          done

      - name: Commit e push su repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add playlist.m3u
          git commit -m "update playlist" || echo "no changes"
          git push
  
  
  
  
