name: Auto IPTV Playlist Stable

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Genera playlist
        run: |
          echo "#EXTM3U" > playlist.m3u

          API="https://api.github.com/repos/sahind01/mutcats/contents/selcuk"

          echo "Scarico lista file..."

          curl -s $API > files.json

          FILES=$(cat files.json | grep -o '"name": *"[^"]*\.m3u8"' | cut -d'"' -f4)

          if [ -z "$FILES" ]; then
            echo "Nessun file trovato"
            exit 0
          fi

          for file in $FILES
          do
            NAME=$(echo $file | sed 's/.m3u8//g' | sed 's/-/ /g')
            URL="https://raw.githubusercontent.com/sahind01/mutcats/main/selcuk/$file"

            echo "#EXTINF:-1,$NAME" >> playlist.m3u
            echo "$URL" >> playlist.m3u
          done

      - name: Upload playlist
        uses: actions/upload-artifact@v4
        with:
          name: playlist
          path: playlist.m3u
  
  
  
  
